services:
  # NestJS Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nest-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - nest-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  nest-network:
    driver: bridge 